### ISSUE TITLE
Something's up with the requirements... 

### ISSUE THREAD

**Issue by everythingability** [app-generator/flask-user-authentication#1]
Error: While importing 'run', an ImportError was raised:

Traceback (most recent call last):
  File "/Users/tomsmith/markingapp5000/env/lib/python3.9/site-packages/flask/cli.py", line 256, in locate_app
    __import__(module_name)
  File "/Users/tomsmith/markingapp5000/run.py", line 6, in <module>
    from app import app, db
  File "/Users/tomsmith/markingapp5000/app/__init__.py", line 10, in <module>
    from flask_login      import LoginManager
  File "/Users/tomsmith/markingapp5000/env/lib/python3.9/site-packages/flask_login/__init__.py", line 16, in <module>
    from .login_manager import LoginManager
  File "/Users/tomsmith/markingapp5000/env/lib/python3.9/site-packages/flask_login/login_manager.py", line 24, in <module>
    from .utils import (login_url as make_login_url, _create_identifier,
  File "/Users/tomsmith/markingapp5000/env/lib/python3.9/site-packages/flask_login/utils.py", line 13, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/Users/tomsmith/markingapp5000/env/lib/python3.9/site-packages/werkzeug/security.py)

(env) Toms-MBP:markingapp5000 tomsmith$ python
Python 3.9.9 (main, Nov 21 2021, 03:23:42) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from werkzeug.security import safe_str_cmp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/Users/tomsmith/markingapp5000/env/lib/python3.9/site-packages/werkzeug/security.py)

**Comment by app-generator** [comment]
Hello @everythingability 

The issue has been fixed in **v0.0.2**.
Please update.

P.S. For more information about the patch: 

- [ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security'](https://blog.appseed.us/how-to-fix-cannot-import-safe_str_cmp-from-werkzeug/)

**Comment by everythingability** [comment]
@app-generator Cor! I thad ried -U but no luck, but that worked a treat. I'm in! 

Thank you very much

**Comment by app-generator** [comment]
Anytime! 
🚀🚀
